---
deployment:
  tasks:
    - export DEPLOYPATH=/home/alsiztec98/public_html/
    - /bin/cp -f index.html $DEPLOYPATH
    - /bin/cp -f dark.html $DEPLOYPATH
    - /bin/cp -f styles.css $DEPLOYPATH
    - /bin/cp -f script.js $DEPLOYPATH
    - /bin/cp -R -f assets $DEPLOYPATH

